travis:
  secure:
    BINSTAR_TOKEN: lrFdcWjuQYZPm0Pl1zuPMKLp1T+UWTM3a6UK8dTnrLrkyuF6/KL98DTOqvMLkgo5MzPvToYu85HjKJZ/Y4Tu7tQVOIU6c8wfwx3V4/hYNPX+2j4lZITzrhfbbYZpdAvk8LeaKDGtPISRDvk5ixL9QPP7B0KNfKx6SresImgQ0/YOyNWmXBUEUck7hxjl3hxmJDS86Gn2xmwctiKdEivOjmMI6a0M56O9DjXKOwNdwuz6aqvTbmq+B12ln3+5eTuPMQxuuc7z8XTwyorxM9RYywFpaaWZGFgF33cTVYKOIkoVKXe+N4Dkav+2aJaSVe0zT5t2gbj3eTGBZVnRATDqHODTSg0SE698Tyf1nW3YLCkCEUAYnHtfCjdPcx2fWlJF9+KPlVypEMKJvbbiLmXmIrjQ8u4Ena001+mSkSvQsTj9gz6Zq1ySzmVoT3o5CV2XgHR3oCL7PxaFausMzmGzaRgGkibYToa8SxlgzT3S94Kss2rDUID8WSB+TwUIH13Z1pAtyz/Ke74gQJHqhJnt9hRghrOieRYadBPUiZ5XvA7xiaxCRXyImEsZNbD1mfddnpZY1ep1/kyPB973WaxZXL1PmxJcFrJYkM0pmIRsV7uEvh47P1VTPEMMFa3qcBKNSrgfymiN7vFVjeUDSgwiFQbzZVfQd7N9PaG5tfJe9qo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
